### ISSUE TITLE
No such file or directory vocab.txt 

### ISSUE THREAD

**Issue by liuxialong** [xubaochuan/dssm#1]
$python train.py 
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from dataProvider import data_provider
  File "../dataProvider/data_provider.py", line 84, in <module>
    vocab = load_vocab()
  File "../dataProvider/data_provider.py", line 72, in load_vocab
    fr = open(vocab_path)
IOError: [Errno 2] No such file or directory: '../../model/vocab.txt'

**Comment by xxllp** [comment]
估计是少了

**Comment by taiyangdixia** [comment]
The same, no vocab.txt....
